// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Otp is the predicate function for otp builders.
type Otp func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// Trip is the predicate function for trip builders.
type Trip func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// VehicleDriver is the predicate function for vehicledriver builders.
type VehicleDriver func(*sql.Selector)
