// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/huydnt1801/chuyende/internal/ent/otp"
	"github.com/huydnt1801/chuyende/internal/ent/predicate"
)

// OtpUpdate is the builder for updating Otp entities.
type OtpUpdate struct {
	config
	hooks    []Hook
	mutation *OtpMutation
}

// Where appends a list predicates to the OtpUpdate builder.
func (ou *OtpUpdate) Where(ps ...predicate.Otp) *OtpUpdate {
	ou.mutation.Where(ps...)
	return ou
}

// SetPhoneNumber sets the "phone_number" field.
func (ou *OtpUpdate) SetPhoneNumber(s string) *OtpUpdate {
	ou.mutation.SetPhoneNumber(s)
	return ou
}

// SetOtp sets the "otp" field.
func (ou *OtpUpdate) SetOtp(s string) *OtpUpdate {
	ou.mutation.SetOtp(s)
	return ou
}

// SetCreatedAt sets the "created_at" field.
func (ou *OtpUpdate) SetCreatedAt(t time.Time) *OtpUpdate {
	ou.mutation.SetCreatedAt(t)
	return ou
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ou *OtpUpdate) SetNillableCreatedAt(t *time.Time) *OtpUpdate {
	if t != nil {
		ou.SetCreatedAt(*t)
	}
	return ou
}

// Mutation returns the OtpMutation object of the builder.
func (ou *OtpUpdate) Mutation() *OtpMutation {
	return ou.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ou *OtpUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, OtpMutation](ctx, ou.sqlSave, ou.mutation, ou.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ou *OtpUpdate) SaveX(ctx context.Context) int {
	affected, err := ou.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ou *OtpUpdate) Exec(ctx context.Context) error {
	_, err := ou.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ou *OtpUpdate) ExecX(ctx context.Context) {
	if err := ou.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ou *OtpUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(otp.Table, otp.Columns, sqlgraph.NewFieldSpec(otp.FieldID, field.TypeInt))
	if ps := ou.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ou.mutation.PhoneNumber(); ok {
		_spec.SetField(otp.FieldPhoneNumber, field.TypeString, value)
	}
	if value, ok := ou.mutation.Otp(); ok {
		_spec.SetField(otp.FieldOtp, field.TypeString, value)
	}
	if value, ok := ou.mutation.CreatedAt(); ok {
		_spec.SetField(otp.FieldCreatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ou.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{otp.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ou.mutation.done = true
	return n, nil
}

// OtpUpdateOne is the builder for updating a single Otp entity.
type OtpUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OtpMutation
}

// SetPhoneNumber sets the "phone_number" field.
func (ouo *OtpUpdateOne) SetPhoneNumber(s string) *OtpUpdateOne {
	ouo.mutation.SetPhoneNumber(s)
	return ouo
}

// SetOtp sets the "otp" field.
func (ouo *OtpUpdateOne) SetOtp(s string) *OtpUpdateOne {
	ouo.mutation.SetOtp(s)
	return ouo
}

// SetCreatedAt sets the "created_at" field.
func (ouo *OtpUpdateOne) SetCreatedAt(t time.Time) *OtpUpdateOne {
	ouo.mutation.SetCreatedAt(t)
	return ouo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ouo *OtpUpdateOne) SetNillableCreatedAt(t *time.Time) *OtpUpdateOne {
	if t != nil {
		ouo.SetCreatedAt(*t)
	}
	return ouo
}

// Mutation returns the OtpMutation object of the builder.
func (ouo *OtpUpdateOne) Mutation() *OtpMutation {
	return ouo.mutation
}

// Where appends a list predicates to the OtpUpdate builder.
func (ouo *OtpUpdateOne) Where(ps ...predicate.Otp) *OtpUpdateOne {
	ouo.mutation.Where(ps...)
	return ouo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ouo *OtpUpdateOne) Select(field string, fields ...string) *OtpUpdateOne {
	ouo.fields = append([]string{field}, fields...)
	return ouo
}

// Save executes the query and returns the updated Otp entity.
func (ouo *OtpUpdateOne) Save(ctx context.Context) (*Otp, error) {
	return withHooks[*Otp, OtpMutation](ctx, ouo.sqlSave, ouo.mutation, ouo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ouo *OtpUpdateOne) SaveX(ctx context.Context) *Otp {
	node, err := ouo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ouo *OtpUpdateOne) Exec(ctx context.Context) error {
	_, err := ouo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ouo *OtpUpdateOne) ExecX(ctx context.Context) {
	if err := ouo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ouo *OtpUpdateOne) sqlSave(ctx context.Context) (_node *Otp, err error) {
	_spec := sqlgraph.NewUpdateSpec(otp.Table, otp.Columns, sqlgraph.NewFieldSpec(otp.FieldID, field.TypeInt))
	id, ok := ouo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Otp.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ouo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, otp.FieldID)
		for _, f := range fields {
			if !otp.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != otp.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ouo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ouo.mutation.PhoneNumber(); ok {
		_spec.SetField(otp.FieldPhoneNumber, field.TypeString, value)
	}
	if value, ok := ouo.mutation.Otp(); ok {
		_spec.SetField(otp.FieldOtp, field.TypeString, value)
	}
	if value, ok := ouo.mutation.CreatedAt(); ok {
		_spec.SetField(otp.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &Otp{config: ouo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ouo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{otp.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ouo.mutation.done = true
	return _node, nil
}
