// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/huydnt1801/chuyende/internal/ent/predicate"
	"github.com/huydnt1801/chuyende/internal/ent/vehicledriver"
)

// VehicleDriverDelete is the builder for deleting a VehicleDriver entity.
type VehicleDriverDelete struct {
	config
	hooks    []Hook
	mutation *VehicleDriverMutation
}

// Where appends a list predicates to the VehicleDriverDelete builder.
func (vdd *VehicleDriverDelete) Where(ps ...predicate.VehicleDriver) *VehicleDriverDelete {
	vdd.mutation.Where(ps...)
	return vdd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (vdd *VehicleDriverDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, VehicleDriverMutation](ctx, vdd.sqlExec, vdd.mutation, vdd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (vdd *VehicleDriverDelete) ExecX(ctx context.Context) int {
	n, err := vdd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (vdd *VehicleDriverDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(vehicledriver.Table, sqlgraph.NewFieldSpec(vehicledriver.FieldID, field.TypeInt))
	if ps := vdd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, vdd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	vdd.mutation.done = true
	return affected, err
}

// VehicleDriverDeleteOne is the builder for deleting a single VehicleDriver entity.
type VehicleDriverDeleteOne struct {
	vdd *VehicleDriverDelete
}

// Where appends a list predicates to the VehicleDriverDelete builder.
func (vddo *VehicleDriverDeleteOne) Where(ps ...predicate.VehicleDriver) *VehicleDriverDeleteOne {
	vddo.vdd.mutation.Where(ps...)
	return vddo
}

// Exec executes the deletion query.
func (vddo *VehicleDriverDeleteOne) Exec(ctx context.Context) error {
	n, err := vddo.vdd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{vehicledriver.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (vddo *VehicleDriverDeleteOne) ExecX(ctx context.Context) {
	if err := vddo.Exec(ctx); err != nil {
		panic(err)
	}
}
