name: Go Lint

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  lint:
    name: Go Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Check gofmt
        run: |
          cd server
          output=$(gofmt -l .)
          if [[ -n "$output" ]]; then
            echo "Code formatting issues found:"
            echo "$output"
            exit 1
          fi

      - name: Run go vet
        run: |
          cd server
          go vet ./...
  unittest:
    name: Unittest
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Run go test
        run: |
          cd server
          go test --tags=integration ./api/server -count=1 -cover -race -v
